### ISSUE TITLE
Eliminar archivos antiguos automáticamente

### ISSUE THREAD

**Issue by DanielRiera** [DanielRiera/counter-visitor-for-woocommerce#3]
Hi,

your plugin creates a lot of files in our case 800.000 in just 10 days, so we had to manualy delete theme. Folders are created here: public_html/wp-content/uploads/wcvtemp/users_qOHQK1pe

How can we disable creation of this or at least automatic clean up every day or hour?

https://wordpress.org/support/topic/creates-files-how-to-disable-this/

**Comment by JoshBour** [comment]
@DanielRiera Hello, is this bug fixed? I'm having the same issue with the temp files not getting removed.
I see that you have committed a fix but it's not on the main branch.
Also, will the plugin be updated to the latest WP version? Thanks

**Comment by DanielRiera** [comment]
Hi! I publish this next week

Thankss
