### ISSUE TITLE
Add new positions, hide on 1 visitor and show via shortcode only

### ISSUE THREAD

**Issue by swspcodes** [DanielRiera/counter-visitor-for-woocommerce#7]
The current positions are limited, and the plugin always shows the counter automatically.

It would be good to add the following positions:

- After product short description
- **Shortcode Only** (hides the automatic display of the counter)

This way, users gain one new default position and they can also show the counter via shortcode only, without it being shown  automatically as it is now

Additionally, it would be nice to be able to hide the counter if there is only one person visiting the product. By leaving the **msgone** field blank for example.

**Comment by DanielRiera** [comment]
1.3.6 version :) Enjoy

**Comment by swspcodes** [comment]
Thanks a lot!!

Will enjoy!

Eduardo
________________________________
